[buildPlans.PrasevkaIomataMnlV2]
family = "Prasevka Iomata MNL v2"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.PrasevkaIomataMnlV2.variants]
  inherits = "ss08"

    [buildPlans.PrasevkaIomataMnlV2.variants.design]
    capital-d = "standard-serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-q = "curly-tailed"
    capital-z = "curly-serifless"
    g = "double-storey"
    l = "serifed"
    m = "earless-corner-double-arch-short-leg-serifless"
    r = "corner-hooked-serifless"
    u = "toothless-rounded-serifless"
    zero = "slashed"
    five = "upright-arched-serifless"
    seven = "curly-serifless"
    punctuation-dot = "square"
    asterisk = "penta-high"
    brace = "curly-flat-boundary"
    guillemet = "curly"
    number-sign = "upright"
    at = "compact"
    dollar = "through"
    cent = "through"
    percent = "rings-segmented-slash"
    lig-neq = "slightly-slanted"

[buildPlans.PrasevkaIomataMnlV2.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.PrasevkaIomataMnlV2.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.PrasevkaIomataMnlV2.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.PrasevkaIomataMnlV2.widths.Normal]
shape = 548
menu = 5
css = "normal"
